### ISSUE TITLE
复旦应统考研请教

### ISSUE THREAD

**Issue by ghost** [HUANGZHIHAO1994/Probability-theory-exercises#1]
学长,我今年考复旦大数据学院的应统.这本书有做过部分题.能要个联系方式交流交流么hhhh

**Comment by HUANGZHIHAO1994** [comment]
如果你要考研的话，千万别学这本，这本理论性太强，也不适合自学。考研的话你真要看概率论就看李贤平的把，如果你只有数三涉及概率论，那么看专门考研的书籍会更有针对性。应统的话专业课也应该只有个数理统计吧，总之你如果是考研的话不要看这本。如果你保研想学习的话，进来选这门课就行了，一般应统选得很少，都是博士和学硕选得，难度较大
